### ISSUE TITLE
crashes game when anvil gui pops up 

### ISSUE THREAD

**Issue by shuutori** [Keyami/KeyScrolls#1]
![image](https://user-images.githubusercontent.com/46617469/102394426-97d29b80-3f8e-11eb-850f-525653e5d95c.png)

my friend in the server can do it but i can't do it myself or else it crashes both my client and then my server goes byebye!

**Comment by Keyami** [comment]
Is this the latest update for the plugin? I submit one the other day for 1.16.4. 

I won't be able to help much until later since I'm at work btw.

**Comment by shuutori** [comment]
i believe so, i downloaded the most recent one on spigot

**Comment by Keyami** [comment]
Alright, could you explain the process in more specific detail?
I've been trying to replicate this and I haven't been able to.

Are you just trying to use a scroll like normal?

Is the crash happening when you craft/use/name the scroll?
Well more specifically, is it happening once the anvil gui opens or when you try to finish naming?

**Comment by Keyami** [comment]
Also would you mind appending the entire log?

**Comment by shuutori** [comment]
my game client freezes as soon as i try to bind the scroll somewhere. 
the anvil gui pops up, which is where exactly it freezes (no time to rename, click things in inventory, etc)
my mouse locks into the window and flashes in the middle of the screen and game client crashes

here's the log
[latest.log](https://github.com/Keyami/KeyScrolls/files/5708512/latest.log)

**Comment by shuutori** [comment]
after the server relaunches, the scroll is bounded to the location but you can't rename it unless you use a real anvil

not really sure whats going on but i want to implement this so bad in my little server w my friends ;_;

**Comment by Keyami** [comment]
Okay so update for you, I have found the issue and I'm working on it as we speak.

**Comment by Keyami** [comment]
So there appears to be a bug with Anvil GUI that crashes servers when interacting with blocks.

Until it's either:
 a.) Fixed by the Anvil GUI dev or
 b.) It's actually me and I fix it some other way

Please use the fix I've pushed to the Spigot page.
All it really does is make it impossible to use scrolls on blocks, so you just need to right-click in the air when using scrolls.

Respond in 24 hours with anymore comments or concerns or I'll be closing the issue tracker, if you experience a different issue or are still having the same one after this patch feel free to open a new issue! 

Thank you so much for liking my plugin enough to go through this!
